interface seedCountry {
  name: string;
  isAvailable: boolean;
  id: string;
}

export const seedCountries: seedCountry[] = [
  { name: "Afghanistan", isAvailable: false, id: "AF" },
  { name: "Aland Islands", isAvailable: false, id: "AX" },
  { name: "Albania", isAvailable: false, id: "AL" },
  { name: "Algeria", isAvailable: false, id: "DZ" },
  { name: "American Samoa", isAvailable: false, id: "AS" },
  { name: "Andorra", isAvailable: false, id: "AD" },
  { name: "Angola", isAvailable: false, id: "AO" },
  { name: "Anguilla", isAvailable: false, id: "AI" },
  { name: "Antarctica", isAvailable: false, id: "AQ" },
  { name: "Antigua and Barbuda", isAvailable: false, id: "AG" },
  { name: "Argentina", isAvailable: false, id: "AR" },
  { name: "Armenia", isAvailable: false, id: "AM" },
  { name: "Aruba", isAvailable: false, id: "AW" },
  { name: "Australia", isAvailable: false, id: "AU" },
  { name: "Austria", isAvailable: false, id: "AT" },
  { name: "Azerbaijan", isAvailable: false, id: "AZ" },
  { name: "Bahamas", isAvailable: false, id: "BS" },
  { name: "Bahrain", isAvailable: false, id: "BH" },
  { name: "Bangladesh", isAvailable: false, id: "BD" },
  { name: "Barbados", isAvailable: false, id: "BB" },
  { name: "Belarus", isAvailable: false, id: "BY" },
  { name: "Belgium", isAvailable: false, id: "BE" },
  { name: "Belize", isAvailable: false, id: "BZ" },
  { name: "Benin", isAvailable: false, id: "BJ" },
  { name: "Bermuda", isAvailable: false, id: "BM" },
  { name: "Bhutan", isAvailable: false, id: "BT" },
  { name: "Bolivia", isAvailable: false, id: "BO" },
  { name: "Bosnia and Herzegovina", isAvailable: false, id: "BA" },
  { name: "Botswana", isAvailable: false, id: "BW" },
  { name: "Bouvet Island", isAvailable: false, id: "BV" },
  { name: "Brazil", isAvailable: false, id: "BR" },
  { name: "British Indian Ocean Territory", isAvailable: false, id: "IO" },
  { name: "Brunei Darussalam", isAvailable: false, id: "BN" },
  { name: "Bulgaria", isAvailable: false, id: "BG" },
  { name: "Burkina Faso", isAvailable: false, id: "BF" },
  { name: "Burundi", isAvailable: false, id: "BI" },
  { name: "Cambodia", isAvailable: false, id: "KH" },
  { name: "Cameroon", isAvailable: false, id: "CM" },
  { name: "Canada", isAvailable: false, id: "CA" },
  { name: "Cape Verde", isAvailable: false, id: "CV" },
  { name: "Cayman Islands", isAvailable: false, id: "KY" },
  { name: "Central African Republic", isAvailable: false, id: "CF" },
  { name: "Chad", isAvailable: false, id: "TD" },
  { name: "Chile", isAvailable: false, id: "CL" },
  { name: "China", isAvailable: false, id: "CN" },
  { name: "Christmas Island", isAvailable: false, id: "CX" },
  { name: "Cocos (Keeling) Islands", isAvailable: false, id: "CC" },
  { name: "Colombia", isAvailable: false, id: "CO" },
  { name: "Comoros", isAvailable: false, id: "KM" },
  { name: "Congo", isAvailable: false, id: "CG" },
  {
    name: "Congo, The Democratic Republic of the",
    isAvailable: false,
    id: "CD",
  },
  { name: "Cook Islands", isAvailable: false, id: "CK" },
  { name: "Costa Rica", isAvailable: false, id: "CR" },
  { name: "Cote D'Ivoire", isAvailable: false, id: "CI" },
  { name: "Croatia", isAvailable: false, id: "HR" },
  { name: "Cuba", isAvailable: false, id: "CU" },
  { name: "Cyprus", isAvailable: false, id: "CY" },
  { name: "Czech Republic", isAvailable: false, id: "CZ" },
  { name: "Denmark", isAvailable: false, id: "DK" },
  { name: "Djibouti", isAvailable: false, id: "DJ" },
  { name: "Dominica", isAvailable: false, id: "DM" },
  { name: "Dominican Republic", isAvailable: false, id: "DO" },
  { name: "Ecuador", isAvailable: false, id: "EC" },
  { name: "Egypt", isAvailable: false, id: "EG" },
  { name: "El Salvador", isAvailable: false, id: "SV" },
  { name: "Equatorial Guinea", isAvailable: false, id: "GQ" },
  { name: "Eritrea", isAvailable: false, id: "ER" },
  { name: "Estonia", isAvailable: false, id: "EE" },
  { name: "Ethiopia", isAvailable: false, id: "ET" },
  { name: "Falkland Islands (Malvinas)", isAvailable: false, id: "FK" },
  { name: "Faroe Islands", isAvailable: false, id: "FO" },
  { name: "Fiji", isAvailable: false, id: "FJ" },
  { name: "Finland", isAvailable: false, id: "FI" },
  { name: "France", isAvailable: false, id: "FR" },
  { name: "French Guiana", isAvailable: false, id: "GF" },
  { name: "French Polynesia", isAvailable: false, id: "PF" },
  { name: "French Southern Territories", isAvailable: false, id: "TF" },
  { name: "Gabon", isAvailable: false, id: "GA" },
  { name: "Gambia", isAvailable: false, id: "GM" },
  { name: "Georgia", isAvailable: false, id: "GE" },
  { name: "Germany", isAvailable: false, id: "DE" },
  { name: "Ghana", isAvailable: false, id: "GH" },
  { name: "Gibraltar", isAvailable: false, id: "GI" },
  { name: "Greece", isAvailable: false, id: "GR" },
  { name: "Greenland", isAvailable: false, id: "GL" },
  { name: "Grenada", isAvailable: false, id: "GD" },
  { name: "Guadeloupe", isAvailable: false, id: "GP" },
  { name: "Guam", isAvailable: false, id: "GU" },
  { name: "Guatemala", isAvailable: false, id: "GT" },
  { name: "Guernsey", isAvailable: false, id: "GG" },
  { name: "Guinea", isAvailable: false, id: "GN" },
  { name: "Guinea-Bissau", isAvailable: false, id: "GW" },
  { name: "Guyana", isAvailable: false, id: "GY" },
  { name: "Haiti", isAvailable: false, id: "HT" },
  { name: "Heard Island and Mcdonald Islands", isAvailable: false, id: "HM" },
  { name: "Holy See (Vatican City State)", isAvailable: false, id: "VA" },
  { name: "Honduras", isAvailable: false, id: "HN" },
  { name: "Hong Kong", isAvailable: false, id: "HK" },
  { name: "Hungary", isAvailable: false, id: "HU" },
  { name: "Iceland", isAvailable: false, id: "IS" },
  { name: "India", isAvailable: false, id: "IN" },
  { name: "Indonesia", isAvailable: false, id: "ID" },
  { name: "Iran, Islamic Republic Of", isAvailable: false, id: "IR" },
  { name: "Iraq", isAvailable: false, id: "IQ" },
  { name: "Ireland", isAvailable: false, id: "IE" },
  { name: "Isle of Man", isAvailable: false, id: "IM" },
  { name: "Israel", isAvailable: false, id: "IL" },
  { name: "Italy", isAvailable: false, id: "IT" },
  { name: "Jamaica", isAvailable: false, id: "JM" },
  { name: "Japan", isAvailable: false, id: "JP" },
  { name: "Jersey", isAvailable: false, id: "JE" },
  { name: "Jordan", isAvailable: false, id: "JO" },
  { name: "Kazakhstan", isAvailable: false, id: "KZ" },
  { name: "Kenya", isAvailable: false, id: "KE" },
  { name: "Kiribati", isAvailable: false, id: "KI" },
  {
    name: "Korea, Democratic People'S Republic of",
    isAvailable: false,
    id: "KP",
  },
  { name: "Korea, Republic of", isAvailable: false, id: "KR" },
  { name: "Kuwait", isAvailable: false, id: "KW" },
  { name: "Kyrgyzstan", isAvailable: false, id: "KG" },
  { name: "Lao People'S Democratic Republic", isAvailable: false, id: "LA" },
  { name: "Latvia", isAvailable: false, id: "LV" },
  { name: "Lebanon", isAvailable: false, id: "LB" },
  { name: "Lesotho", isAvailable: false, id: "LS" },
  { name: "Liberia", isAvailable: false, id: "LR" },
  { name: "Libyan Arab Jamahiriya", isAvailable: false, id: "LY" },
  { name: "Liechtenstein", isAvailable: false, id: "LI" },
  { name: "Lithuania", isAvailable: false, id: "LT" },
  { name: "Luxembourg", isAvailable: false, id: "LU" },
  { name: "Macao", isAvailable: false, id: "MO" },
  {
    name: "Macedonia, The Former Yugoslav Republic of",
    isAvailable: false,
    id: "MK",
  },
  { name: "Madagascar", isAvailable: false, id: "MG" },
  { name: "Malawi", isAvailable: false, id: "MW" },
  { name: "Malaysia", isAvailable: false, id: "MY" },
  { name: "Maldives", isAvailable: false, id: "MV" },
  { name: "Mali", isAvailable: false, id: "ML" },
  { name: "Malta", isAvailable: false, id: "MT" },
  { name: "Marshall Islands", isAvailable: false, id: "MH" },
  { name: "Martinique", isAvailable: false, id: "MQ" },
  { name: "Mauritania", isAvailable: false, id: "MR" },
  { name: "Mauritius", isAvailable: false, id: "MU" },
  { name: "Mayotte", isAvailable: false, id: "YT" },
  { name: "Mexico", isAvailable: false, id: "MX" },
  { name: "Micronesia, Federated States of", isAvailable: false, id: "FM" },
  { name: "Moldova, Republic of", isAvailable: false, id: "MD" },
  { name: "Monaco", isAvailable: false, id: "MC" },
  { name: "Mongolia", isAvailable: false, id: "MN" },
  { name: "Montserrat", isAvailable: false, id: "MS" },
  { name: "Morocco", isAvailable: false, id: "MA" },
  { name: "Mozambique", isAvailable: false, id: "MZ" },
  { name: "Myanmar", isAvailable: false, id: "MM" },
  { name: "Namibia", isAvailable: false, id: "NA" },
  { name: "Nauru", isAvailable: false, id: "NR" },
  { name: "Nepal", isAvailable: false, id: "NP" },
  { name: "Netherlands", isAvailable: false, id: "NL" },
  { name: "Netherlands Antilles", isAvailable: false, id: "AN" },
  { name: "New Caledonia", isAvailable: false, id: "NC" },
  { name: "New Zealand", isAvailable: false, id: "NZ" },
  { name: "Nicaragua", isAvailable: false, id: "NI" },
  { name: "Niger", isAvailable: false, id: "NE" },
  { name: "Nigeria", isAvailable: false, id: "NG" },
  { name: "Niue", isAvailable: false, id: "NU" },
  { name: "Norfolk Island", isAvailable: false, id: "NF" },
  { name: "Northern Mariana Islands", isAvailable: false, id: "MP" },
  { name: "Norway", isAvailable: false, id: "NO" },
  { name: "Oman", isAvailable: false, id: "OM" },
  { name: "Pakistan", isAvailable: false, id: "PK" },
  { name: "Palau", isAvailable: false, id: "PW" },
  { name: "Palestinian Territory, Occupied", isAvailable: false, id: "PS" },
  { name: "Panama", isAvailable: false, id: "PA" },
  { name: "Papua New Guinea", isAvailable: false, id: "PG" },
  { name: "Paraguay", isAvailable: false, id: "PY" },
  { name: "Peru", isAvailable: true, id: "PE" },
  { name: "Philippines", isAvailable: false, id: "PH" },
  { name: "Pitcairn", isAvailable: false, id: "PN" },
  { name: "Poland", isAvailable: false, id: "PL" },
  { name: "Portugal", isAvailable: false, id: "PT" },
  { name: "Puerto Rico", isAvailable: false, id: "PR" },
  { name: "Qatar", isAvailable: false, id: "QA" },
  { name: "Reunion", isAvailable: false, id: "RE" },
  { name: "Romania", isAvailable: false, id: "RO" },
  { name: "Russian Federation", isAvailable: false, id: "RU" },
  { name: "RWANDA", isAvailable: false, id: "RW" },
  { name: "Saint Helena", isAvailable: false, id: "SH" },
  { name: "Saint Kitts and Nevis", isAvailable: false, id: "KN" },
  { name: "Saint Lucia", isAvailable: false, id: "LC" },
  { name: "Saint Pierre and Miquelon", isAvailable: false, id: "PM" },
  { name: "Saint Vincent and the Grenadines", isAvailable: false, id: "VC" },
  { name: "Samoa", isAvailable: false, id: "WS" },
  { name: "San Marino", isAvailable: false, id: "SM" },
  { name: "Sao Tome and Principe", isAvailable: false, id: "ST" },
  { name: "Saudi Arabia", isAvailable: false, id: "SA" },
  { name: "Senegal", isAvailable: false, id: "SN" },
  { name: "Serbia and Montenegro", isAvailable: false, id: "CS" },
  { name: "Seychelles", isAvailable: false, id: "SC" },
  { name: "Sierra Leone", isAvailable: false, id: "SL" },
  { name: "Singapore", isAvailable: false, id: "SG" },
  { name: "Slovakia", isAvailable: false, id: "SK" },
  { name: "Slovenia", isAvailable: false, id: "SI" },
  { name: "Solomon Islands", isAvailable: false, id: "SB" },
  { name: "Somalia", isAvailable: false, id: "SO" },
  { name: "South Africa", isAvailable: false, id: "ZA" },
  {
    name: "South Georgia and the South Sandwich Islands",
    isAvailable: false,
    id: "GS",
  },
  { name: "Spain", isAvailable: false, id: "ES" },
  { name: "Sri Lanka", isAvailable: false, id: "LK" },
  { name: "Sudan", isAvailable: false, id: "SD" },
  { name: "Suriname", isAvailable: false, id: "SR" },
  { name: "Svalbard and Jan Mayen", isAvailable: false, id: "SJ" },
  { name: "Swaziland", isAvailable: false, id: "SZ" },
  { name: "Sweden", isAvailable: false, id: "SE" },
  { name: "Switzerland", isAvailable: false, id: "CH" },
  { name: "Syrian Arab Republic", isAvailable: false, id: "SY" },
  { name: "Taiwan, Province of China", isAvailable: false, id: "TW" },
  { name: "Tajikistan", isAvailable: false, id: "TJ" },
  { name: "Tanzania, United Republic of", isAvailable: false, id: "TZ" },
  { name: "Thailand", isAvailable: false, id: "TH" },
  { name: "Timor-Leste", isAvailable: false, id: "TL" },
  { name: "Togo", isAvailable: false, id: "TG" },
  { name: "Tokelau", isAvailable: false, id: "TK" },
  { name: "Tonga", isAvailable: false, id: "TO" },
  { name: "Trinidad and Tobago", isAvailable: false, id: "TT" },
  { name: "Tunisia", isAvailable: false, id: "TN" },
  { name: "Turkey", isAvailable: false, id: "TR" },
  { name: "Turkmenistan", isAvailable: false, id: "TM" },
  { name: "Turks and Caicos Islands", isAvailable: false, id: "TC" },
  { name: "Tuvalu", isAvailable: false, id: "TV" },
  { name: "Uganda", isAvailable: false, id: "UG" },
  { name: "Ukraine", isAvailable: false, id: "UA" },
  { name: "United Arab Emirates", isAvailable: false, id: "AE" },
  { name: "United Kingdom", isAvailable: false, id: "GB" },
  { name: "United States", isAvailable: false, id: "US" },
  {
    name: "United States Minor Outlying Islands",
    isAvailable: false,
    id: "UM",
  },
  { name: "Uruguay", isAvailable: false, id: "UY" },
  { name: "Uzbekistan", isAvailable: false, id: "UZ" },
  { name: "Vanuatu", isAvailable: false, id: "VU" },
  { name: "Venezuela", isAvailable: false, id: "VE" },
  { name: "Viet Nam", isAvailable: false, id: "VN" },
  { name: "Virgin Islands, British", isAvailable: false, id: "VG" },
  { name: "Virgin Islands, U.S.", isAvailable: false, id: "VI" },
  { name: "Wallis and Futuna", isAvailable: false, id: "WF" },
  { name: "Western Sahara", isAvailable: false, id: "EH" },
  { name: "Yemen", isAvailable: false, id: "YE" },
  { name: "Zambia", isAvailable: false, id: "ZM" },
  { name: "Zimbabwe", isAvailable: false, id: "ZW" },
];
